feat(svg): add Configure unocss svg collections configuration and dem…
antdv-pro/antdv-pro pull request #107
Opened 2023-09-30 06:47 UTC by wcySpring

add Configure unocss svg collections configuration and demo page

新增了 unocss svg配置，增加了使用案例 `feat/icon/index.vue`

2023-10-01 03:14 UTC, kirklin requested changes

2023-10-01 03:14 UTC, kirklin commented on package.json
> +    "@unocss/preset-icons": "^0.56.4",
这个依赖可以去掉，因为unocss包含了这个，所以不需要重复添加依赖

2023-10-01 03:14 UTC, kirklin commented on src/pages/feat/icon/index.vue
> +<script setup lang="ts"></script>
文件名是index.vue的时候可不可以加上`defineOptions`呢

2023-10-01 03:14 UTC, kirklin commented on src/pages/feat/icon/index.vue
图标如果单独加demo可以做的更好一些，一是引用unocss图标的可以封装成一个组件。放在components/icons下。第二个是可以参考卡片列表多列一点图标出来。

2023-10-01 07:49 UTC, wcySpring commented on src/pages/feat/icon/index.vue
unocss svg使用上都是通过 unocss 提供 css 原子 进行样式上的效果。封装组件的话 所能暴露出来的属性 原因小于 css本身，但如果固定属性来说 感觉缺少了 灵活性。 
在组件封装这里 有什么建议么

2023-10-01 08:31 UTC, wcySpring commented on src/pages/feat/icon/index.vue
多列出一些图标 ，unocss 提供本地还使用 iconify ，是需要列出更多 iconify 的图标么

2023-10-01 08:57 UTC, kirklin commented on src/pages/feat/icon/index.vue
对的，本地的举个例子就可以，可以动态取点iconify 的图标，这样子好看一点。

2023-10-01 08:58 UTC, kirklin commented on src/pages/feat/icon/index.vue
组件主要是方便统一一下不同方案之间图标的样式，比如ant design的图标，还有unocss的图标这种，封装组件可以保持一致性

2023-10-02 10:06 UTC, wcySpring commented on package.json
> +    "@unocss/preset-icons": "^0.56.4",
已经移除

2023-10-02 10:06 UTC, wcySpring commented on src/pages/feat/icon/index.vue
> +<script setup lang="ts"></script>
已经增加

2023-10-02 10:07 UTC, wcySpring commented on src/pages/feat/icon/index.vue
增加了了 更多demo 但是 unocss 静态编译的特殊性 我还没着手 开始组件编写 可以提出一个新的 feat svg 全局组件的新任务的，这个任务对我来说现在还有点没太想好

2023-10-02 14:37 UTC, kirklin commented on src/pages/feat/icon/index.vue
最新的代码存在栈溢出的情况，请检查。

2023-10-03 04:53 UTC, wcySpring commented
如果你想做动态加载 svg 显然 unocss 不是好的选择，由于 UnoCSS 在构建时使用静态提取，在编译时我们不可能知道所有实用程序的组合 因此需要提前注册 safelist 
这类问题参考  https://github.com/unocss/unocss/issues?q=dynamic+class 
解决方法：https://unocss.dev/guide/extracting#safelist
unocss svg 也会每次增加额外的svg 的请求，推荐是固定不需要动态加载，并且svg 图片较小的业务使用

2023-10-03 04:54 UTC, wcySpring commented on src/pages/feat/icon/index.vue
重新提交 增加了node 溢出问题，原因是动态导入 案例加载的svg过多导致的

2023-10-07 01:01 UTC, aibayanyu20 commented
这个先等等再说，等明确下来在做合并

2023-10-07 01:30 UTC, wcySpring commented
> 这个先等等再说，等明确下来在做合并

要是动态svg 还是给像之前提到的

`unplugin-icons`  `vite-plugin-svg-icons` `@iconify/vue` 

集成进去虽然关于他们优缺点

`unplugin-icons` , 能够识别本地 svg 文件，并且可以配合 iconify 图标库，利用 `unplugin-auto-import` 可以实现自动下载 使用到的 iconify 图标集

`vite-plugin-svg-icons`, 针对本地 svg 图标插件管理，通过配合 封装的 svg 组件，利用其精灵图的特性可以优化 svg 数量

`@iconify/vue`,一个已经封装好的 vue 组件用来直接使用  iconify 图标库，支持cdn 加载图片，并且会将加载后的图标存储在本地，也可以使用 本地下载好的 iconify 图标库

这三种是优选，unocss 弊端是还会 增加svg 图片请求连接。小批量上来说确实 unocss 可能还算方便，但是大量切动态加载上目前我感觉是不合适的

2023-11-26 07:01 UTC, closed without merging